FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app

RUN pip install --user -r requirements.txt

RUN apt-get update && apt-get install -y \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY . .

ENV PORT=8000

EXPOSE 8000

CMD ["python", "telegram_voice.py"]
